### ISSUE TITLE
 assert exists(wav_path) AssertionError

### ISSUE THREAD

**Issue by Yuancheng1314** [nnsvs/nnsvs#142]
assert exists(wav_path)
AssertionError

**Comment by taroushirani** [comment]
Hello.

First of all, the information provided is too little to answer.  At least you should post the following information, or you will never get any answer.

1. Platform you used(Windows, Linux, Macintosh, or Google Colaboratory etc.)
2. The version of NNSVS and related packages
3. Singing voice database you used
4. Detailed instruction you did and whole error message you got.
