### ISSUE TITLE
train_acoustic entry point missing from setup.py

### ISSUE THREAD

**Issue by hetteric** [nnsvs/nnsvs#154]
The setup.py file appears to contain entry points to scripts that no longer exist in nnsvs, such as `nnsvs-train-resf0` but lack the current `nnsvs-train-acoustic`. Adding this to setup.py for very slightly easier usage would be appreciated.

**Comment by r9y9** [comment]
Thank you for the report. You are right. I will fix it soon.

**Comment by r9y9** [comment]
This should be fixed now. If you find any new bugs, please let me know.
