### ISSUE TITLE
Add DiffSinger configurations and recipes to reproduce experiments reported in NNSVS documentation

### ISSUE THREAD

**Issue by JellyBrick** [nnsvs/nnsvs#161]
To reproduce https://r9y9.github.io/projects/nnsvs/

**Comment by r9y9** [comment]
https://github.com/nnsvs/DiffSinger Code and configs should be ready. I'll add a brief instruction on how to train DiffSInger models.

**Comment by JellyBrick** [comment]
> #164 Added a guide. Should be reproducible now.

```python
RuntimeError: Error(s) in loading state_dict for GaussianDiffusion:
        size mismatch for fs2.encoder_embed_tokens.weight: copying a param with shape torch.Size([48, 256]) from checkpoint, the shape in current model is torch.Size([63, 256]).
        size mismatch for fs2.encoder.embed_tokens.weight: copying a param with shape torch.Size([48, 256]) from checkpoint, the shape in current model is torch.Size([63, 256]).
```

`--infer` fails with this error. It seems that the code or configuration for inference is not uploaded to [this repository](https://github.com/nnsvs/DiffSinger).

**Comment by r9y9** [comment]
What command(s) did you try? I cannot reproduce and `--infer` works fine for me.

**Comment by JellyBrick** [comment]
```bash
CUDA_VISIBLE_DEVICES=0 python tasks/run.py --config usr/configs/midi/e2e/opencpop/ds100_adj_rel_ritsu_v3_ritsu_pe.yaml --exp_name 0923_ds100_adj_rel_ritsu_v3_ritsu_pe --reset --infer
```

and

```bash
CUDA_VISIBLE_DEVICES=0 python inference/svs/ds_e2e.py --config usr/configs/midi/e2e/opencpop/ds100_adj_rel_ritsu_v3_ritsu_pe.yaml --exp_name 0923_ds100_adj_rel_ritsu_v3_ritsu_pe
```

**Comment by r9y9** [comment]
I was unable to reproduce with the first command. The second one is not supported as it is hardcoded for Chinese. https://github.com/MoonInTheRiver/DiffSinger/blob/5f2f6eb3c42635f9446363a302602a2ef1d41d70/inference/svs/ds_e2e.py#L50-L55
