### ISSUE TITLE
Cannot install nnsvs

### ISSUE THREAD

**Issue by eugeborzone** [nnsvs/nnsvs#196]
I've tried to install it with the docs command (pip install -e ".[dev,lint,test]") with
Ubuntu 22.04
and
Python3.10,3.9,3.8 and 3.7
always show:
ERROR: Could not build wheels for nnmnkwii, pysptk, pysinsy, pyworld, which is required to install pyproject.toml-based projects

**Comment by r9y9** [comment]
should be solved by the latest release
